- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Repos
      dnf:
        update_cache: true
  gather_facts: yes
  vars_prompt:
    - name: "vault_password"
      prompt: "Enter vault password"
      private: yes
  tasks:
    - include_tasks: ./tasks/ssh.yml
    - include_tasks: ./tasks/zsh.yml
    - include_tasks: ./tasks/nix.yml
