        - name: Decrypt ssh.yml file
          ansible.builtin.command: ansible-vault decrypt ../vaults/ssh.yml --output=ssh_private_key
          vars:
            ansible_become_pass: "{{ vault_password }}"
          no_log: true
          tags:
            - ssh
        - name: Copy ssh key to local machine
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/ssh_private_key"
            dest: "~/.ssh/id_rsa"
            mode: '0600'
          delegate_to: localhost
          tags:
            - ssh
